### ISSUE TITLE
Labels are no longer shown

### ISSUE THREAD

**Issue by skosch** [benfred/venn.js#107]
Since updating to 0.2.16 my circles don't have labels anymore. I can get them back by manually adding `label: sets[0]` to my elements, but just having the `sets` in there used to be enough. Sorry I don't have enough time to hunt this down and submit a PR this week, but maybe you have an idea?

**Comment by benfred** [comment]
Sorry about that - broke it in a previous commit.

Fixed here:  https://github.com/benfred/venn.js/commit/f86fb6ab74cb6887eec7dc543754f611c6e80743 and have pushed to npm.

**Comment by skosch** [comment]
Fastest fix ever! Thanks a ton Ben.
