### ISSUE TITLE
How to get data object on click ?

### ISSUE THREAD

**Issue by kristoff2016** [benfred/venn.js#110]
Hello thanks for great plugin. I am looking for the way how to get data objects when user clicked on each cycles. 
example: onclick="myfunc(data)"

func myfunc(data) {
   console.log('data here', data)
}
thanks for your helps 
thanks

**Comment by benfred** [comment]
I think you're looking something like this (assuming the diagram is in a div with id=venn)
```javascript
d3.selectAll("#venn .venn-circle")
    .on("click", function(data) {
        console.log(data);
});
```

**Comment by kristoff2016** [comment]
Hi Thanks for your replied. I will try it and let's you know
