### ISSUE TITLE
Fix "donut" chart when smaller set is contained in bigger set

### ISSUE THREAD

**Issue by leelokas** [benfred/venn.js#120]
Remove or add option to turn off "donut" chart. It seems to happen with some distinct numbers e.g. when the subset size is 1538995, 1539000, 1539008 or 1539018.

![selection_670](https://user-images.githubusercontent.com/5443662/36379024-b66d2834-1585-11e8-97de-fbb739517b11.png)

**Comment by benfred** [comment]
Whats the problem here? Is it that you'd rather the A set be off to one side in the diagram?

**Comment by leelokas** [comment]
Yes. As the subset circle is usually positioned to one side, I would prefer it acted this way for all inputs for a more consistent behaviour.

**Comment by benfred** [comment]
Should be fixed in the latest version (also the 'C' set won't show up unnecessarily anymore).
<img width="820" alt="screen shot 2018-02-20 at 10 23 40 am" src="https://user-images.githubusercontent.com/69536/36441676-279051b0-1628-11e8-9b47-128236f690f0.png">
