### ISSUE TITLE
Get root <svg> element

### ISSUE THREAD

**Issue by dima74** [benfred/venn.js#123]
Could you say, please, how can I in JavaScript get root `<svg>` element, which is added by Venn.js?

**Comment by benfred** [comment]
This example adds a 'defs' section to the svg (to add a drop shadow): https://github.com/benfred/venn.js/blob/master/examples/styled.html#L103

**Comment by dima74** [comment]
Thank you, if I understand correctly you propose use `d3.select("#main_div_id svg")`.

I am having a bit different situation, I am trying to include Venn.js diagramm into existing svg. So my svg structure looks like this:

```
<svg id="main-svg">
  ... some elements, for example <g> or <svg> ...
  <svg> // this is Venn.js root element
    <g class="venn-area venn-circle" data-venn-sets="0">...</g>
    ...
  </svg>
</svg>
```

Maybe I should use `:nth-child()` and so on, but can you say, please, maybe there is a better solution.

**Comment by dima74** [comment]
Thank you for response!

> If you pass a valid SVG element to the venn diagram, it will use it instead of creating a new one.

So I just copy your example to create [this gist](https://bl.ocks.org/dima74/b64f348cf233d1d17706efa701348c10/7032d279a7d8122b1abc81f27eca2d7398be36ca) and looks like new `<svg>` element still creates:

![image](https://user-images.githubusercontent.com/6505554/38579648-543d8340-3d10-11e8-92ae-8cfeb8adcbd0.png)

Could you say, please, what I miss?

**Comment by benfred** [comment]
You didn't miss anything - I gave you bad information (didn't test too closely =(. The element here ```d3.select("#venn")``` is always the parent of the svg, not the the svg itself.

However, using the same javascript and updating the html to:

```
<body>
<svg  width=800 height=800><g id="venn"><svg id="for_real_this_time"></svg></g></svg></div>
</body>
```

And venn.js won't create a new SVG element, and just use the one thats already created as the child of the d3.select("#venn") call:

<img width="508" alt="screen shot 2018-04-10 at 2 57 24 pm" src="https://user-images.githubusercontent.com/69536/38585677-8b0dc042-3ccf-11e8-9d26-094665163d09.png">

**Comment by dima74** [comment]
Yes, thank you!

I am summarize this as [StackOverflow answer](https://stackoverflow.com/questions/49764071/get-root-svg-element/49764072)
