### ISSUE TITLE
Is there a version working with d3 v3x ?

### ISSUE THREAD

**Issue by openStove** [benfred/venn.js#125]
Is there a version working with d3 v3x ? I try to integrate with powerbi, but the extension only supports   D3.js version is v3.5.17

**Comment by benfred** [comment]
Everything here should work with both D3 v3 and D3 v4 - we go out of our way to support both versions here (hacks like this: https://github.com/benfred/venn.js/blob/master/src/diagram.js#L27).

If you change any of the examples to load d3 v3 instead they should just work :

```
diff --git a/examples/simple.html b/examples/simple.html
index 1220ab6..e213993 100644
--- a/examples/simple.html
+++ b/examples/simple.html
@@ -15,7 +15,7 @@ body {
     <div id="venn"></div>
 </body>
 
-<script src="https://d3js.org/d3.v4.min.js"></script>
+<script src="https://d3js.org/d3.v3.min.js"></script>
 <script src="../venn.js"></script>
 <script>
 // define sets and set set intersections
```
