### ISSUE TITLE
Dependent d3 version5 for venn.js

### ISSUE THREAD

**Issue by jitendrahpatwa** [benfred/venn.js#148]
Please share the dependent venn.js implementation for d3 version 5.
Tried changing scale ordinal functions as in venn.js for accordingly with version 5 of d3 but throwing many issues.

**Comment by sgratzl** [comment]
have you tried my fork at https://github.com/upsetjs/venn.js

**Comment by jitendrahpatwa** [comment]
Thanks your forks works well and also with some changes and modification works with benfred/venn.js.
