### ISSUE TITLE
Uncaught initial bisect points must have opposite signs 

### ISSUE THREAD

**Issue by mpelikan** [benfred/venn.js#16]
I have been having a problem with an exception being thrown from venn.js with various datasets. These datasets appear to be valid sets.

I have create a JSFiddle with a simplified example that generates the exception:
http://jsfiddle.net/mpelikan/F8cL3

**Comment by ylaizet** [comment]
Hello,

I have the same error with the following data on the current master branch code:

Group1 : 66
Group2 : 86
Group3 : 573
Group1,Group2 : 9
Group1,Group3 : 66
Group2,Group3 : 86
Group1,Group2,Group3 : 9

It's related to the "Group1,Group3" which fully overlap the Group1. If put 65 as value for "Group1,Group3", I get rid of the error.

Regards

**Comment by benfred** [comment]
Its working for me =(. This code:
```
var sets = [
{sets: ['Group1'], size: 66},
{sets: ['Group2'], size: 86},
{sets: ['Group3'], size: 573},
{sets: ['Group1','Group2'], size: 9},
{sets: ['Group1','Group3'], size: 66},
{sets: ['Group2','Group3'], size: 86},
{sets: ['Group1','Group2','Group3'], size: 9}]

var chart = venn.VennDiagram();
d3.select("#venn").datum(sets).call(chart);
```
Produces this output:
<img width="381" alt="screen shot 2016-05-26 at 9 19 59 am" src="https://cloud.githubusercontent.com/assets/69536/15581864/0f4548da-2323-11e6-894c-f65158c04621.png">

**Comment by ylaizet** [comment]
Hello,

my mistake indeed. I figured out that the conversion of my data to the variable sets was setting the size value as an array with the size value instead of a integer directly.
I apologize for that and thanks.

**Comment by Hadh** [comment]
For future reference, this error could also be generated when you are passing your data as strings in the "Size" parameter:
`{sets: ['Group1'], size: "66" },` => generates : Uncaught initial bisect points must have opposite signs 
Make sure : size: 66
