### ISSUE TITLE
Cannot Set Maximum size

### ISSUE THREAD

**Issue by perara** [benfred/venn.js#28]
Good Morning!

I cannot seem to set a maximum radius for a circle. 
Sometimes i have very distant data with a relativly small intersection.

This causes the smaller sized object to be nearly invisible.
Manually setting the radius misplaces the diagram totally.

Any way to set a max size/minimum size for a circle?

Thanks!

**Comment by benfred** [comment]
Probably easier to set a minimum size here - I would do something like 

d3.selectAll("circle").attr("r", function(d) { return min(d.radius, 10); } 

to put a lower bound on this

**Comment by avnersch** [comment]
@benfred Tried using your suggestion to set minimum radius size, but with no luck.
This is what I used:
```
d3.selectAll(".venn-circle").attr("r", function(d) {
    return 10;
});
```
I see that an "r=10" attribute is added to the rendered path.venn-circle but it doesn't affect the circle size.
Tried with differrent values (10,100,1000) - no change.
Is there a way to set a minimum circle size with the library these days?
