### ISSUE TITLE
Glitch intersecting 3 sets of 4

### ISSUE THREAD

**Issue by fkiller** [benfred/venn.js#31]
I was creating a Venn diagram depicting two sets(A,C) intersecting with one set(D) with one separated set (total of 4), but ```{set: [2,3], size:1}``` isn't applied.

```
var sets = 
    [
    {label: "A", size: 20}, {label: "B", size: 10},
    {label: "C", size: 10}, {label: "D", size: 10}
    ],
    overlaps = [
        {sets: [0,1], size: 0},
        {sets: [0,2], size: 0},
        {sets: [0,3], size: 1},
        {sets: [1,2], size: 0},
        {sets: [1,3], size: 0},
        {sets: [2,3], size: 1},
        {sets: [0,1,2], size: 0},
        {sets: [0,1,3], size: 0},
        {sets: [0,2,3], size: 0}
    ];
```

Below is an exact code.
http://fiddle.jshell.net/fkiller/qfc5xtbk/4/

With set of 3(A,C,D), it works fine.

http://fiddle.jshell.net/fkiller/qfc5xtbk/6/

**Comment by benfred** [comment]
Try getting the latest code from master, I think this commit will have fixed https://github.com/benfred/venn.js/commit/5b38382797df34449e86b803cdd29ea830b54c78

**Comment by benfred** [comment]
verified works with latest code, closing
