### ISSUE TITLE
updateD3Diagram doesn't create/destroy new sets

### ISSUE THREAD

**Issue by benfred** [benfred/venn.js#32]

**Comment by danpaulsmith** [comment]
It's not updating my diagram either...

updateD3Diagram(diagram, vennObj)...

It realigns the diagram as if a new circle is there, but no elements are added to the svg.

**Comment by benfred** [comment]
@danpaulsmith there is a fix in the branch 'new_api' (see https://github.com/benfred/venn.js/commit/14a4acb2301f00ebae9b1af00da9e0983e2c4512). Its not quite ready for merging, there are a couple other issues outstanding but this case should be handled there.

**Comment by danpaulsmith** [comment]
Yep working in new_api branch :thumbsup:

**Comment by benfred** [comment]
Merged
