### ISSUE TITLE
.style('font-size', ...) not working in 'new_api'

### ISSUE THREAD

**Issue by stewartlord** [benfred/venn.js#34]
I am able to apply other text styles, such as font-style, but not font-size. The following reproduces the problem for me:

```
<!doctype html>
<html lang="en">
<body></body>
<script src="http://d3js.org/d3.v2.min.js"></script>
<script src="../venn.js"></script>
<script>
var data = [{
  sets: ['A'],
  size:  10
}];
var diagram = venn.VennDiagram().width(600).height(400);
d3.select("body").datum(data).call(diagram);
d3.selectAll("body .venn-circle text")
  .style("font-size", "24px")
  .style("font-style", "italic");
</script>
</html>
```

**Comment by benfred** [comment]
Short term fix is to pass the font-size in to the venn diagram directly:

```
var diagram = venn.VennDiagram().fontSize("24px");
d3.select("body").datum(data).call(diagram);
```

This isn't ideal, its the only style property where this is necessary. Right now the VennDiagram object needs to know the text size for the label wrapping code, and also to handle transitions for new sets. Its the transitioning code thats preventing setting the size afterwards - even for brand new diagrams, all the elements are transitioning from a state of font-size:0px to the supplied value. This lets new circles grow from nothing from the middle of the diagram. 

Alternatively we could just remove the font-size handling entirely, like 

```
diff --git a/venn.js b/venn.js
index 59772b4..e4c9470 100644
--- a/venn.js
+++ b/venn.js
@@ -73,7 +73,6 @@
                     .style("fill-opacity", ".25");
 
                 enter.append("text")
-                    .style("font-size", "0px")
                     .style("fill", function(d) { return d.sets.length == 1 ?
                     colours(label(d)) : "#444"; })
                     .text(function (d) { return label(d); } )
@@ -88,7 +87,6 @@
                     .attrTween("d", pathTween);
 
                 update.select("text")
-                    .style("font-size", fontSize)
                     .text(function (d) { return label(d); } )
                     .each("end", venn.wrapText(circles, label))
                     .attr("x", function(d) {
```

But this would cause other issues with text wrapping, and new circles having their labels appear before the rest of the circle does.

I'm not sure what the best solution here is really, but will have something better in place before I merge this into master.

**Comment by stewartlord** [comment]
The work-around solves the problem for me :) I wish I could provide more thoughtful feedback on the problem. I'm afraid I don't know enough about the underlying code to offer any intelligent opinions.

**Comment by benfred** [comment]
So - the workaround I came up with is to only transition font-size if you explicitly do a 'fontSize' call on the venn-diagram. This means for most people it will work like expected - but for use cases where you want to have labels grow from nothing (when creating new sets) - you can pass the desired font-size in to the venn diagram. Fix is in this commit: https://github.com/benfred/venn.js/commit/46d5108cb67acf5bc663cbef3314d5d4937d24cb
