### ISSUE TITLE
If there is no intersection, intersection labels are drawn in top-left (in 'new_api')

### ISSUE THREAD

**Issue by stewartlord** [benfred/venn.js#35]

**Comment by benfred** [comment]
This should be fixed by https://github.com/benfred/venn.js/commit/46d5108cb67acf5bc663cbef3314d5d4937d24cb

Overlapped intersection areas will have labels in the right place now, non-existant areas will log a message saying there was an issue - and place the area well offscreen

**Comment by stewartlord** [comment]
:+1:
