### ISSUE TITLE
Venn Digram Appears Very Small

### ISSUE THREAD

**Issue by sudeesh** [benfred/venn.js#36]
Hi Ben,

Thanks for a wonderful venn js. We have used it in our project it helped a lot.

But in some scenario the diagram appears very small. 
This happens when the radius is very small also the positions come out in the left bottom corner or right top corner.

Could you please help me with it?

http://codepen.io/ghiden/pen/bGAIg

Put the following code in the above link
{
"sets":
[
{"label":"Query1","size":21},
{"label":"Query2","size":13501},{"label":"Query3","size":13013},{"label":"Query4","size":9697},{"label":"Query5","size":11690}],
"overlaps":
[
{"sets":[0,1],"size":14},
{"sets":[0,2],"size":10},
{"sets":[0,3],"size":6},
{"sets":[0,4],"size":4},
{"sets":[1,2],"size":12131},
{"sets":[1,3],"size":8580},
{"sets":[1,4],"size":10749},
{"sets":[2,3],"size":9011},
{"sets":[2,4],"size":10209},
{"sets":[3,4],"size":7220},
{"sets":[0,1,2],"size":8},
{"sets":[0,1,3],"size":4},
{"sets":[0,1,4],"size":4},
{"sets":[0,2,3],"size":4},
{"sets":[0,2,4],"size":3},
{"sets":[0,3,4],"size":2},
{"sets":[1,2,3],"size":8031},
{"sets":[1,2,4],"size":9528},
{"sets":[1,3,4],"size":6533},
{"sets":[2,3,4],"size":6856},
{"sets":[0,1,2,3],"size":3},
{"sets":[0,1,2,4],"size":3},
{"sets":[0,1,3,4],"size":2},
{"sets":[0,2,3,4],"size":2},
{"sets":[1,2,3,4],"size":6201},
{"sets":[0,1,2,3,4],"size":2}
]
}

Thanks,
Kiran Nakhale

**Comment by benfred** [comment]
Thanks!

The code thats embedded in that codepen.io link is pretty old - and I've made some layout fixes recently that seem to fix this problem (changes 5b38382797df34449e86b803cdd29ea830b54c78 and f4d1bd5b7e7bab5896b1f230cf23b11d7db60262 ).  If you get the most recent version from master here this problem should be solved

**Comment by sudeesh** [comment]
Hi Ben,

Thanks for the quick reply.
The new js worked for the above combination.
But it didnt work for the following combination

I had put this following combination in medical.jsonp in ur examples.

Attached is the screen shot. Could you please help me with it.

var sets = 
[{"label":"Query1","size":319},{"label":"Query2","size":190699},{"label":"Query3","size":176264},{"label":"Query4","size":133190},{"label":"Query5","size":166900}],
overlaps=[{"sets":[0,1],"size":140},{"sets":[0,2],"size":80},{"sets":[0,3],"size":61},{"sets":[0,4],"size":65},{"sets":[1,2],"size":161382},{"sets":[1,3],"size":116554},{"sets":[1,4],"size":153169},{"sets":[2,3],"size":96592},{"sets":[2,4],"size":133562},{"sets":[3,4],"size":98480},{"sets":[0,1,2],"size":58},{"sets":[0,1,3],"size":42},{"sets":[0,1,4],"size":50},{"sets":[0,2,3],"size":28},{"sets":[0,2,4],"size":32},{"sets":[0,3,4],"size":31},{"sets":[1,2,3],"size":86859},{"sets":[1,2,4],"size":124987},{"sets":[1,3,4],"size":89285},{"sets":[2,3,4],"size":66847},{"sets":[0,1,2,3],"size":23},{"sets":[0,1,2,4],"size":29},{"sets":[0,1,3,4],"size":27},{"sets":[0,2,3,4],"size":16},{"sets":[1,2,3,4],"size":62540},{"sets":[0,1,2,3,4],"size":16}];

![specshare](https://cloud.githubusercontent.com/assets/5012691/6186830/f8d4d35c-b3a4-11e4-9259-e28ab1590b9c.png)


Thanks,
Kiran Nakhale

**Comment by sudeesh** [comment]
Can you check this link. I have pasted the code in this JSFiddle.
http://fiddle.jshell.net/09c10qae/2/

**Comment by sudeesh** [comment]
Hi Ben,

If in case the following observation helps. 

Following set does not work with latest js but it used to work with old js
var sets =
[{"label":"Query1","size":319},{"label":"Query2","size":190699},{"label":"Query3","size":176264},{"label":"Query4","size":133190},{"label":"Query5","size":166900}],
overlaps=[{"sets":[0,1],"size":140},{"sets":[0,2],"size":80},{"sets":[0,3],"size":61},{"sets":[0,4],"size":65},{"sets":[1,2],"size":161382},{"sets":[1,3],"size":116554},{"sets":[1,4],"size":153169},{"sets":[2,3],"size":96592},{"sets":[2,4],"size":133562},{"sets":[3,4],"size":98480},{"sets":[0,1,2],"size":58},{"sets":[0,1,3],"size":42},{"sets":[0,1,4],"size":50},{"sets":[0,2,3],"size":28},{"sets":[0,2,4],"size":32},{"sets":[0,3,4],"size":31},{"sets":[1,2,3],"size":86859},{"sets":[1,2,4],"size":124987},{"sets":[1,3,4],"size":89285},{"sets":[2,3,4],"size":66847},{"sets":[0,1,2,3],"size":23},{"sets":[0,1,2,4],"size":29},{"sets":[0,1,3,4],"size":27},{"sets":[0,2,3,4],"size":16},{"sets":[1,2,3,4],"size":62540},{"sets":[0,1,2,3,4],"size":16}];

Following set does not work old js but it works with latest js
{
"sets":
[
{"label":"Query1","size":21},
{"label":"Query2","size":13501},{"label":"Query3","size":13013},{"label":"Query4","size":9697},{"label":"Query5","size":11690}],
"overlaps":
[
{"sets":[0,1],"size":14},
{"sets":[0,2],"size":10},
{"sets":[0,3],"size":6},
{"sets":[0,4],"size":4},
{"sets":[1,2],"size":12131},
{"sets":[1,3],"size":8580},
{"sets":[1,4],"size":10749},
{"sets":[2,3],"size":9011},
{"sets":[2,4],"size":10209},
{"sets":[3,4],"size":7220},
{"sets":[0,1,2],"size":8},
{"sets":[0,1,3],"size":4},
{"sets":[0,1,4],"size":4},
{"sets":[0,2,3],"size":4},
{"sets":[0,2,4],"size":3},
{"sets":[0,3,4],"size":2},
{"sets":[1,2,3],"size":8031},
{"sets":[1,2,4],"size":9528},
{"sets":[1,3,4],"size":6533},
{"sets":[2,3,4],"size":6856},
{"sets":[0,1,2,3],"size":3},
{"sets":[0,1,2,4],"size":3},
{"sets":[0,1,3,4],"size":2},
{"sets":[0,2,3,4],"size":2},
{"sets":[1,2,3,4],"size":6201},
{"sets":[0,1,2,3,4],"size":2}
]
}

Thanks,
Kiran Nakhale

**Comment by benfred** [comment]
I see whats going on here, but its actually relatively complicated to fix in general. There is no exact solution for this input (any euler diagram with more than 4 or more circles can't represent the data exactly unless there are disjoint areas (0 size) which you don't have here). 

The easiest workaround here is probably to switch over to a MDS initial layout (see the mds.html example). Alternatively you could use reduce the stepsize in the fmin call by going like:

    sets = venn.venn(sets, overlaps, {nonZeroDelta: 1.01});

I don't have time to work on this right now, but will get a proper fix in a couple of weeks maybe.

**Comment by sudeesh** [comment]
Hi Ben,

Any update on this issue

**Comment by benfred** [comment]
Did the workaround I suggested work for you?

**Comment by benfred** [comment]
So, I think you were hitting this issue (5b38382797df34449e86b803cdd29ea830b54c78) causing a bad solution to be picked (with one set being disjoint). That should be fixed now.

Additionally, I added some code to move disjoint circles close to rest of the diagram here (0f9b02c26964fa21c645cd1cf1cd6f9ab53c56f9) which should fix the problem if it happens in a different circumstance
