### ISSUE TITLE
Issue with multiple overlapping circles

### ISSUE THREAD

**Issue by winterismute** [benfred/venn.js#41]
Hi, we have found this nice library some time ago when we wanted to make a small prototype involving visualization of overlapping resources, and I have to say it worked very well with some test data :DHowever, while trying to visualize some different dataset we encountered some issues.
One can be easily reproduced using the interactive.html example and this json object: http://pastebin.com/mhVjDP5G
You can see that we have, on one side, 2 sets ("SB4", "Git") containing all 1 element, and also intersecting each other (they count the people working on those projects, which is just the same for those 2). Same situation for the sets "Search" and "The Editor". We have then the "ITOps" set which has one element and disconnected from everything. In the end, we have the "Sbx" set which contains the 2 persons (size = 2) but also intersects everything by "ITOps".
What I would expect is something similar to this pic (excuse the terrible quality): http://i.imgur.com/d0yZ8P7.png?1
Two couples of circles completely overlapping, one circle containing all of them, one circle outside, disconnected.
Unfortunately, with the standard constructor vennjs fails and throws a strange error. With the "classicMDSLayout", the result is just plain wrong.
I know this is probably a very annoying problem, but the library is pretty nice and we would like to use it, hence any pointer on where to start to solve this case would be greatly appreciated.
Thanks,

**Comment by benfred** [comment]
So - the issue is that you need to specify that sets aren't intersecting for all pairs of sets - by passing a '0' size here. The error message came out garbled (I'll fix that later) but that is what its trying to say..

You get this output:
<img width="524" alt="screen shot 2015-07-22 at 8 41 09 am" src="https://cloud.githubusercontent.com/assets/69536/8829847/bc51f4ca-304d-11e5-87e7-cb3b959c494b.png">

When passing this input

```
// define sets and set set intersections
var sets = [
  {sets: ["Sbx"], size: 4},
  {sets: ["SB4"], size: 1},
  {sets: ["Git"], size: 1},
  {sets: ["Search"], size: 1},
  {sets: ["The Editor"], size: 1},
  {sets: ["ITOps"], size: 1},
  {sets: ["Sbx", "SB4"], size: 1},
  {sets: ["Sbx", "Git"], size: 1},
  {sets: ["Sbx", "Search"], size: 1},
  {sets: ["Sbx", "The Editor"], size: 1},
  {sets: ["Sbx", "ITOps"], size: 0},
  {sets: ["SB4", "Git"], size: 1},
  {sets: ["SB4", "Search"], size: 0},
  {sets: ["SB4", "The Editor"], size: 0},
  {sets: ["SB4", "ITOps"], size: 0},
  {sets: ["Git", "Search"], size: 0},
  {sets: ["Git", "The Editor"], size: 0},
  {sets: ["Git", "ITOps"], size: 0},
  {sets: ["Search", "The Editor"], size: 1},
  {sets: ["Search", "ITOps"], size: 0},
];
```
 The classic MDS layout is no longer necessary  and has been removed from the documentation, [see this post](http://www.benfrederickson.com/better-venn-diagrams/) for details on why.

**Comment by winterismute** [comment]
Thank you for your quick reply!
Your example does work, although you did forget to specify one pair:
{sets: ["ITOps", "The Editor"], size: 0}

However, now, if I have to specify ALL the intersections, also the empty ones, I feel like I'm in trouble: in your example you left the out intersections between 3 (or more) sets, but sometimes they do carry some meaning (or am I wrong?), does it mean I have to specify all the permutation(n, k) where k = 2..n-1 (so triplets, quadruplets and so on)?

Another not related question: might it be that the resulting chart depends on the order in which the set intersections are given in the array? It seemed to me that by scrambling them I could get wrong results, but maybe it was just an impression...
Thank you in any case for your time!

**Comment by benfred** [comment]
You shouldn't have to specify all the missing areas after this change: https://github.com/benfred/venn.js/commit/050d9adf9c2bd85c98374d25c93cedc524e2bbf7

**Comment by Dachaz** [comment]
Thanks, this removes the error but raises a question about rendering. If you compare @winterismute's pastie and your code snippet, there is one crucial difference: your size for sbx is 4, while we have 2, which produces this rendering: 
![screenshot from 2015-09-30 12 35 43](https://cloud.githubusercontent.com/assets/124358/10190843/c9457c98-676f-11e5-9a32-8f7f1a92c02b.png)

To motivate this data sample with the real situation: 
* We observe 3 people in total.
  * 1 person is in ITops team.
  * The remaining 2 are in SBX team. 
    * One of those people is also in Search and The Editor teams;
    * The other one is in SB4 and Git teams. 

From this example, you would agree that the rendering is wrong as:
* There should be no overlap of Search/The Editor with Git/SB4
* Both Search/The Editor and Git/SB4 should not go outside Sbx (as they are fully contained within Sbx)

Of course, this is not our full data model, but it contains a lot of corner-cases like this.

Do you have any ideas/suggestions on how to tackle this? Any input would be greatly appreciated!

**Comment by benfred** [comment]
All the circles produced as output here have areas that are proportional to the set sizes. This means that a set of size 2 will have a radius that is about 1.41 times as big as a set of size 1. For your example, that means that the 'Editor' and 'SB4' circles can't fit inside the 'Sbx' circle without overlapping each other. 

This library tries to produce the best possible approximation of this input - which is whats shown. Given the constraints you've specified there is no way to produce output that matches.
