### ISSUE TITLE
Always need to specify overlap information

### ISSUE THREAD

**Issue by sebastianstoelen** [benfred/venn.js#42]
Hi, 

This is more a question than an issue really. Do I need to specify overlap information for every possible combination? I'm working with a lot of data, but not necessary a lot of overlap. Is there any way that I don't need to specify the overlap for every possible combination, only for the ones that do overlap? When I don't give information about the overlap of a certain combination, I get the error message "Need overlap information for set {"x":10000000000,"y":10000000000,"size":1,"radius":0.5641895835477563}".

Thanks in advance

**Comment by benfred** [comment]
Right now you need to specify overlaps for every pairwise combination - but don't combinations of 3+ sets.

I'm going to fix the error message so its more descriptive, and remove this constraint (missing values will be assumed to of size 0) - hopefully this weekend. Also see https://github.com/benfred/venn.js/issues/42

**Comment by sompylasar** [comment]
@benfred Any update on this issue?

**Comment by sebastianstoelen** [comment]
Well, I was creating sets greater than 3 combinations, so I fixed that and now I’m using just 3 entries. I now specify information for all possible combinations of these entries, so I just worked around it.

**Comment by sompylasar** [comment]
@sebastianstoelen I worked this around, too, by adding all the pairs missing from my input data with the size of 0. I wanted to ask the project maintainer if he's going to fix the issue or have already done this.

**Comment by benfred** [comment]
@sompylasar @sebastianstoelen this should be fixed now - sorry about the delay

**Comment by sompylasar** [comment]
@benfred great, many thanks!
