### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jfresco** [benfred/venn.js#44]
I need to use this module in a project that don't have `bower` on its buildchain, but uses `npm` instead. I think with little effort the module can be ready for publish.

**Comment by benfred** [comment]
I published to npm here - https://www.npmjs.com/package/venn.js

I haven't tested running this code in node, but in theory the file 'src/export.js' should be adding to module.exports if there is no window present. Let me know if it this works =).

**Comment by jfresco** [comment]
Thanks! I'll let you know if something goes wrong.
