### ISSUE TITLE
Don't use the set name as a class

### ISSUE THREAD

**Issue by Calvein** [benfred/venn.js#50]
I have a problem with it because if one of the set has a space it will add a couple of classes, e.g:
This set `my set` will render a circle with this classes `venn-area venn-circle venn-sets-my set`.
`.set` should be here really.

I have a couple of solutions:

Exposing the label function https://github.com/benfred/venn.js/blob/master/src/diagram.js#L135-L142

Or, better, add an attribute instead of a class (at https://github.com/benfred/venn.js/blob/master/src/diagram.js#L69-L73).
It would be replacing this:

```js
var enter = nodes.enter()
    .append('g')
    .attr("class", function(d) {
        return "venn-area venn-" +
            (d.sets.length == 1 ? "circle" : "intersection") +
            (" venn-sets-" + d.sets.join("_"));
    });
```

by

```js
var enter = nodes.enter()
    .append('g')
    .attr("class", function(d) {
        return "venn-area venn-" +
            (d.sets.length == 1 ? "circle" : "intersection");
    })
    .attr("data-venn-sets", function(d) {
        return d.sets.join("_");
    });
```

**Comment by benfred** [comment]
looks good! thanks!
