### ISSUE TITLE
A possible method of displaying the elements in a mathematically meaningful way

### ISSUE THREAD

**Issue by ben-pr-p** [benfred/venn.js#52]
I am thinking of a display in which each of the elements contained within the sets have their own little circles, and the arrangement of the elements means something about the data. 

It would require a user supplied distance function such that for every pair of elements it is possible to determine a desired distance between them.

So, you've got your sets:
```
A = [1, 2, 3, 4]
B = [3, 4, 5, 6]
```
And your distance function:
```
distanceBetweenElements(el1, el2): el1 - el2
```
The desired result would be two circles with one intersection area and 6 circles with 1-6 on them inside their respective places in the Venn Diagram. And, the layout of these 6 circles is such that the visual distance between `el1` and `el2` is the best possible approximation of the result of the distance function.

So, you would expect `2` and `5` to be closer to the intersection area of `A` and `B` than `1` and `6`. 

This is a more complicated optimization problem, but the work is significantly reduced by the fact that the number of possible places an element can go is limited by the arrangements of the sets – one only needs to position elements in relation to other elements in the same intersection area, not all elements.

To simplify it further, an aggregate distance function could be used 
```
distanceBetweenElAndSet(el, set): 
     average distance between (el, otherEl) for otherEl in set
```
Then there are as many smaller optimization problems as there are meaningful set intersections.

Eh?

**Comment by benfred** [comment]
I can see the value in displaying set members inside the venn diagram - though I'm unsure about the whole user supplied distance metric thing

**Comment by christophe-g** [comment]
This might address the issue ; )

**Comment by benfred** [comment]
@christophe-g solution seems to do a good job at this - closing
