### ISSUE TITLE
Any tutorial or readme how to use it in windows

### ISSUE THREAD

**Issue by Shicheng-Guo** [benfred/venn.js#59]
Any tutorial or readme how to use it in windows or linux? You know, lots of guys don't familiar with Java programming. Thanks.

**Comment by benfred** [comment]
The README file has info on using,  hopefully its pretty simple to get going. There are a bunch of examples in the examples folder, take a look at [http://benfred.github.io/venn.js/examples/simple.html](http://benfred.github.io/venn.js/examples/simple.html) for basic usage.
