### ISSUE TITLE
Provide pre-transpiled code on npm

### ISSUE THREAD

**Issue by skosch** [benfred/venn.js#62]
Thanks for this wonderful little tool!

Do you think it'd be possible to provide the npm version in ES5? Most anyone using this from within webpack likely has a setup similar to
```
{
  test: /\.js?$/,
  exclude: /(node_modules|bower_components)/,
  loader: 'babel?presets[]=es2015' // etc.
}
```
... because there is an unspoken expectation that anything inside `node_modules` doesn't use `export from` lines etc.

Not a big deal, but would be nice not to have to mess with the webpack config for just this one package.

**Comment by benfred** [comment]
Thanks!

So, there is a transpiled ES5 version installed in node_modules/venn.js/venn.js  . Its produced with rollup.js as detailed in this post on creating D3 plugins: https://bost.ocks.org/mike/d3-plugin/

I'm not really a JS guy though, so let me know if I'm doing anything wrong here =)

**Comment by skosch** [comment]
I seems I spoke too soon. It works without any problems on another machine of mine, just as you described. For some mysterious reason though the first one insists on loading `index.js`, and webpack complains about needing a loader (i.e. babel) to deal with `export from` lines.

I'll be taking another look at this; for now thanks again for a great library and sorry about the false alarm!
