### ISSUE TITLE
Add width / height arguments

### ISSUE THREAD

**Issue by bf** [benfred/venn.js#63]
Could we make width and height customizable for the SVG element? I don't find any option to do it.

**Comment by benfred** [comment]
You should be able to set the width/height on the VennDiagram object like:
```
var chart = venn.VennDiagram()
                 .width(600)
                 .height(500);
```
See [examples/dynamic.html](http://benfred.github.io/venn.js/examples/dynamic.html) for a demo

**Comment by bf** [comment]
Thanks!

**Comment by JackConnor** [comment]
Thanks! This is a big one, it might make sense to throw this into the main documentation. Great job!
