### ISSUE TITLE
Can i make all possible combinations in JSON array sets;

### ISSUE THREAD

**Issue by RahulMysore** [benfred/venn.js#67]
When i change the code of JSON array to combine 3 companies, that is Radiohead, Bach and Eminem i.e., [0,7,4] sets in JSON array, the changes of new intersection among these 3 companies does not reflect in the Venn diagram.
the changes in the JSON array is as follows ~~> "  {"sets": [0, 4, 7], "size": 110},  "   
 
please help me understand if there is any possibility that may overcome the above issue ?

**Comment by benfred** [comment]
Its an optimization process - its impossible to show diagrams like that one correctly, so its trying to do the best possible representation. I suspect that changing that area isn't sufficient to make a difference in the final layout.

Specifying an optional weight here can give this area extra importance in the optimization process. There is an example here http://benfred.github.io/venn.js/examples/weighted.html
