### ISSUE TITLE
Custom svg size

### ISSUE THREAD

**Issue by ELind77** [benfred/venn.js#72]
Hi,

I love this library and I think that it's a great complement to the functionality of d3 and I'm glad to see development continuing.  

Is there some way to adjust the size of the final layout?  I want the whole thing to be bigger.

-- Eric

**Comment by benfred** [comment]
thanks! 

you can specify the width/height on the diagram. take a look at https://github.com/benfred/venn.js/issues/63 for details

**Comment by ELind77** [comment]
Thanks! This is exactly what I needed. Should have looked through the closed issues.
