### ISSUE TITLE
module support

### ISSUE THREAD

**Issue by parauchf** [benfred/venn.js#73]
I would like to implement this package, but seems like it is looking for D3 as a global.  This makes it a bit awkward to use in projects using some kind of module loader.  From what I understand, D3 detects the presence of an AMD loader and if found, refrains from creating a global (https://github.com/d3/d3/issues/1693).

Would you be interested in a PR to make this work with AMD style projects?

**Comment by benfred** [comment]
If you're interested in putting that together - that would be awesome =)

**Comment by parauchf** [comment]
Cool, might take me a week or two, but I'll take a crack.  I personally don't understand the landscape of js package loaders, so have to do some learning.

**Comment by aethant** [comment]
Any movement on this? I'm running into a similar issue.

**Comment by parauchf** [comment]
Hi @aethant, I applied the same temporary fix in my code.  I will eventually get to this, but I can't say just when...

**Comment by benfred** [comment]
So - I've enabled d3 4.0 support in this commit: https://github.com/benfred/venn.js/commit/a308b391aece84cda82f8ae58521251f3021f97c . I'm hoping that this will also work with amd modules now since I'm importing d3 rather than assuming a global is defined.  Let me know =)

**Comment by aethant** [comment]
Sorry, I was on another project. Just wanted to update: the support for d3 4.0 worked. Able to use the module without the previous workarounds. Thank you!

**Comment by benfred** [comment]
good to hear! glad its working
