### ISSUE TITLE
Firefox shadow bug

### ISSUE THREAD

**Issue by missingdays** [benfred/venn.js#74]
In your [example](http://benfred.github.io/venn.js/examples/styled.html) circles with shadow are not visible (the 4th chart)
I'm using FireFox v47
With Chromium everything is good. 
Weird thing is that no error is shown in console.

**Comment by benfred** [comment]
Hmm - this definitely used to work in firefox, but doesn't seem to now.  Removing the          ```areas.attr("filter", "url(#dropshadow)");``` line makes it show up again

**Comment by benfred** [comment]
Last commit should fix - Thanks for pointing this out!
