### ISSUE TITLE
D3 4.0?

### ISSUE THREAD

**Issue by skosch** [benfred/venn.js#75]
A more modularized version of d3 has come out – is there a chance you'll be able to provide an upgraded version of this amazing little library?

**Comment by benfred** [comment]
We changed this to use the new d3 plugin architecture (https://bost.ocks.org/mike/d3-plugin/) late last year: https://github.com/benfred/venn.js/pull/54 

I haven't tested out with d3 4.0 yet, or even looked into whats involved. It shouldn't be too hard to get going though

**Comment by benfred** [comment]
I've switched over to using d3 4.0 here:
https://github.com/benfred/venn.js/commit/a308b391aece84cda82f8ae58521251f3021f97c

**Comment by skosch** [comment]
Whoa, nice – I hadn't even seen your other reply yet, but that's impressive. Thank you!
