### ISSUE TITLE
3 way overlaps drawn when there 3x2 way interactions

### ISSUE THREAD

**Issue by navatintarev** [benfred/venn.js#78]
The data contains three sets that all interact with each other pairwise, but there is no three way interaction. This is inferred and results in a joint overlapping area that should not be there.
These exist:
{Drama,Romance} 
{Comedy,Romance} 
{Comedy,Drama}   

This does not exist:
{Drama,Romance,Comedy}

What it looks like:
![screen shot 2016-08-12 at 17 41 12](https://cloud.githubusercontent.com/assets/329504/17629886/b45f0d00-60b4-11e6-8853-850fc2867258.png)

Where the issue is:
![no_overlap](https://cloud.githubusercontent.com/assets/329504/17629887/b6f9d540-60b4-11e6-8868-81d84a9d88e9.jpg)

**Comment by Novalis80** [comment]
you are right. the problem is, this can not be solved with circles. this is: if you want to sick to relative correct size.

**Comment by benfred** [comment]
So - the results here are an approximation process. Like I said in the 3rd and 4th paragraph of [my blog post introducing this project](http://www.benfrederickson.com/venn-diagrams-with-d3.js/):

> The problem is that even for only 3 sets, its not always possible to position everything so that everything is area proportional to the set sizes. Try changing A=B=C=8 , AB=AC=4 and BC=0 in the above example to see what I mean about impossible layouts. There is no way to exactly satisfy all those constraints. Even worse is trying to layout Euler diagrams with 4+ sets: if there are no disjoint sets, its actually impossible to use circles to represent these set relations exactly.
> 
> I still want the best possible approximation even if its not possible to be perfect all the time. So I did the sensible thing here: define a function that measures how well a layout matches the desired overlaps - and then minimize that function numerically.
> 

In your case, It doesn't look like there is a better layout for that data.
