### ISSUE TITLE
5 sets venn diagram is not displaying all intersections correctly

### ISSUE THREAD

**Issue by tonytomk** [benfred/venn.js#82]
Hi Team,

we have created a 5 set Venn diagram please find below the plunker link

http://embed.plnkr.co/1Am7Sq8UwvuDUNvBooVY/

the resulting venn diagram became set A centric,
because its not able to plot the intersection between  D&E,D&C,B&E,C&D etc

we have tried for a 5 set venn diagram like this

![5sets](https://cloud.githubusercontent.com/assets/19387522/18658521/708558d8-7f21-11e6-8b78-778cb7fb6946.png)

please let us know how to resolve this issue,
and how we can integrate venn.js to typescript applications ??

Thanks in advance
Tony

**Comment by benfred** [comment]
If there are no disjoint sets, its impossible to show all the different set relationships for 4+ sets using circles (try to draw a diagram with 4 circles where every circle overlaps the other twice, and you won't be able to because placing the 4th circle means it will only have a pairwises intersection with 2 out of the 3 other circles). I mentioned this briefly in the [original post](http://www.benfrederickson.com/venn-diagrams-with-d3.js/), but maybe wasn't super clear.

You might be better offer using a [chord diagram](https://bl.ocks.org/mbostock/4062006)

I don't use typescript so can't help you there

**Comment by tonytomk** [comment]
Hi benfred,
Thanks for the reply, I will check the details :)

**Comment by netflowauditor** [comment]
This  set worked for me

var sets = [ {sets: ['A'], size: 6},
             {sets: ['B'], size: 6},
             {sets: ['C'], size: 6},
             {sets: ['D'], size: 6},
             {sets: ['E'], size: 6},
             
             {sets: ['A','B'], size: 6},
             {sets: ['B','C'], size: 6},
             {sets: ['C','D'], size: 6},
             {sets: ['D','E'], size: 6},
             {sets: ['E','A'], size: 6},
            
             {sets: ['A','B','C','D','E'], size: 6},
             ];

Cheers
Rafi

<img width="368" alt="CySight - venn - github" src="https://user-images.githubusercontent.com/62791190/154346700-c3db4753-2bdf-48f8-8ace-513d61bd2498.png">

**Comment by netflowauditor** [comment]
Simply changing the A-E size to 6 also does the trick

var sets = [ {sets: ['A'], size: 6},
             {sets: ['B'], size: 6},
             {sets: ['C'], size: 6},
             {sets: ['D'], size: 6},
             {sets: ['E'], size: 6},
             
             {sets: ['A','B'], size: 2},
             {sets: ['A','C'], size: 2},
             {sets: ['A','D'], size: 2},
             {sets: ['A','E'], size: 2},
             {sets: ['B','C'], size: 2},
             {sets: ['B','D'], size: 2},
             {sets: ['C','D'], size: 2},
             {sets: ['C','E'], size: 2},
             {sets: ['D','E'], size: 2},
             {sets: ['B','E'], size: 2},
            
             {sets: ['A','B','C'], size: 2}, 
             {sets: ['A','B','D'], size: 2}, 
             {sets: ['A','B','E'], size: 2}, 
             {sets: ['B','C','D'], size: 2}, 
             {sets: ['B','D','E'], size: 2}, 
             {sets: ['C','D','E'], size: 2},
             {sets: ['D','E','A'], size: 2},
             
             {sets: ['A','B','C','D'], size: 2}, 
             {sets: ['A','B','C','E'], size: 2}, 
             {sets: ['B','C','D','E'], size: 2},
             {sets: ['D','E','C','A'], size: 2}, 
             {sets: ['E','C','A','D'], size: 2}, 
             {sets: ['A','B','D','E'], size: 2},
              {sets: ['A','B','C','D','E'], size: 2},
             ];
