### ISSUE TITLE
Is there any way to know when the layout calculation finished?

### ISSUE THREAD

**Issue by zxhfighter** [benfred/venn.js#83]
when i changed data to rerender, the layout calculation seems to be a aync operation, Is there any way to know when the layout calculation finished?

**Comment by benfred** [comment]
Modifying the ['dynamic'](http://benfred.github.io/venn.js/examples/dynamic.html) example like this:

```javascript
d3.selectAll("input").on("change", function() {
    var diagram = venn.VennDiagram()
    var layout = diagram(d3.select("#venn").datum(getSetIntersections()));
    layout.update.on("end", function() { console.log("finished!") })
});
```

will call console.log when the animation finishes
