### ISSUE TITLE
Display 3 sets, A with 2 elements and B and C disjoint subsets of A with 1 elem each

### ISSUE THREAD

**Issue by vrandezo** [benfred/venn.js#86]
When I choose the following set:
A: 2, B:1, C:1,
AB: 1, AC: 1, BC:0,
ABC: 0

I expect the B and C to be covering A entirely, have no overlap with each other, and remain fully within A.

None of these conditions is fulfilled.

I understand that this is a limitation of the circle-based approach. Is there a JS library I can use that actually displays the sets correctly?

**Comment by benfred** [comment]
There is a pretty comprehensive set of resources here: http://www.cvast.tuwien.ac.at/SetViz
