### ISSUE TITLE
Export the plot

### ISSUE THREAD

**Issue by arupgsh** [benfred/venn.js#94]
Is there a way to export the Venn digram as a PNG or JPEG image?

**Comment by benfred** [comment]
This library doesn't support this - but other people have published examples online on how to do this

The easiest way is probably to extract the generated SVG file using a tool like http://nytimes.github.io/svg-crowbar/ and then convert the SVG to a PNG using an image editor

Alternatively, there are some demos on how to do this with code:

https://bl.ocks.org/mbostock/6466603
http://bl.ocks.org/vicapow/758fce6aa4c5195d24be
http://bl.ocks.org/Rokotyan/0556f8facbaf344507cdc45dc3622177

**Comment by arupgsh** [comment]
Thans for the info
