### ISSUE TITLE
Intersection of 3 sets missing [Union of Empty Sets]

### ISSUE THREAD

**Issue by snowbreeze** [benfred/venn.js#98]
I cant figure out why this is happening. I have three sets, all intersect with each other. However the intersection of all of them is not showing. For example.

![screen shot 2017-07-27 at 9 32 33 pm](https://user-images.githubusercontent.com/8898721/28680411-e6c4e3e2-7313-11e7-8af8-8fbd710ad208.png)

```
var sets = [
  {
    "sets": [
      "Present"
    ],
    "size": 10,
    "label": "Present"
  },
  {
    "sets": [
      "Holiday"
    ],
    "size": 1,
    "label": "Holidays"
  },
  {
    "sets": [
      "WeeklyOff"
    ],
    "size": 12,
    "label": "Weekly Offs"
  },
  {
    "sets": [
      "Present",
      "Holiday",
      "WeeklyOff"
    ],
    "size": 1
  },
  {
    "sets": [
      "Present",
      "Holiday"
    ],
    "size": 0
  },
  {
    "sets": [
      "Present",
      "WeeklyOff"
    ],
    "size": 1
  },
  {
    "sets": [
      "WeeklyOff",
      "Holiday"
    ],
    "size": 0
  }
]
```

If you see the intersection of all the three is not happening. 

Are these solutions possible?
![img_20170727_220840690](https://user-images.githubusercontent.com/8898721/28681824-71187492-7318-11e7-9d88-2d0a39e39fd8.jpg)

**Comment by benfred** [comment]
```size: 0``` in your code snippet above indicates that you want the 'holidays' set to be disjoint from the other two sets. It should be ```size: 1``` instead
